# Generated by Django 3.0.5 on 2020-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200702_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='title_genre', to='api.Genres'),
        ),
    ]
