# Generated by Django 3.0.5 on 2020-07-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200709_1126'),
        ('api', '0005_titles_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
