# Generated by Django 3.0.5 on 2020-07-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_titles_genre'),
        ('comment', '0002_auto_20200709_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Titles'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
