# Generated by Django 3.0.5 on 2020-07-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200709_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='titles',
        ),
    ]
